// <auto-generated />
using System;
using AlessandroGozzi.BookECommerce.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlessandroGozzi.BookECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831120604_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingsNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("_shipmentIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ShipmentIds");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShippedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.Book", b =>
                {
                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.ValueObjects.ImageUrl", "MainPhoto", b1 =>
                        {
                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("MainPhotoUrl");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Price");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsMany("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.ValueObjects.BookReview", "Reviews", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Rating")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("BookId");

                            b1.ToTable("BookReviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookId");

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.FullName", "CustomerName", b2 =>
                                {
                                    b2.Property<int>("BookReviewId")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("BookReviewId");

                                    b2.ToTable("BookReviews");

                                    b2.WithOwner()
                                        .HasForeignKey("BookReviewId");

                                    b2.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Name", "Name", b3 =>
                                        {
                                            b3.Property<int>("FullNameBookReviewId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("CustomerFirstName");

                                            b3.HasKey("FullNameBookReviewId");

                                            b3.ToTable("BookReviews");

                                            b3.WithOwner()
                                                .HasForeignKey("FullNameBookReviewId");
                                        });

                                    b2.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Surname", "Surname", b3 =>
                                        {
                                            b3.Property<int>("FullNameBookReviewId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("CustomerLastName");

                                            b3.HasKey("FullNameBookReviewId");

                                            b3.ToTable("BookReviews");

                                            b3.WithOwner()
                                                .HasForeignKey("FullNameBookReviewId");
                                        });

                                    b2.Navigation("Name")
                                        .IsRequired();

                                    b2.Navigation("Surname")
                                        .IsRequired();
                                });

                            b1.Navigation("CustomerName")
                                .IsRequired();
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.ValueObjects.ISBN", "ISBNCode", b1 =>
                        {
                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("TEXT")
                                .HasColumnName("ISBN");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.ValueObjects.Subject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Subject");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.Navigation("ISBNCode")
                        .IsRequired();

                    b.Navigation("MainPhoto")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Reviews");

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Carts.Cart", b =>
                {
                    b.OwnsMany("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Carts.CartItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BookTitle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CartId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("SellerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("CartId");

                            b1.ToTable("CartItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.ValueObjects.ImageUrl", "MainPhoto", b2 =>
                                {
                                    b2.Property<Guid>("CartItemId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MainPhotoUrl");

                                    b2.HasKey("CartItemId");

                                    b2.ToTable("CartItems");

                                    b2.WithOwner()
                                        .HasForeignKey("CartItemId");
                                });

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("CartItemId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Price");

                                    b2.HasKey("CartItemId");

                                    b2.ToTable("CartItems");

                                    b2.WithOwner()
                                        .HasForeignKey("CartItemId");
                                });

                            b1.Navigation("MainPhoto")
                                .IsRequired();

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.Customer", b =>
                {
                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CAP")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("CAP");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("City");

                            b1.Property<string>("CivicNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("CivicNumber");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Name", "Name", b2 =>
                                {
                                    b2.Property<Guid>("FullNameCustomerId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("FirstName");

                                    b2.HasKey("FullNameCustomerId");

                                    b2.ToTable("Customers");

                                    b2.WithOwner()
                                        .HasForeignKey("FullNameCustomerId");
                                });

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Surname", "Surname", b2 =>
                                {
                                    b2.Property<Guid>("FullNameCustomerId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("LastName");

                                    b2.HasKey("FullNameCustomerId");

                                    b2.ToTable("Customers");

                                    b2.WithOwner()
                                        .HasForeignKey("FullNameCustomerId");
                                });

                            b1.Navigation("Name")
                                .IsRequired();

                            b1.Navigation("Surname")
                                .IsRequired();
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.PhoneNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.CreditCard", "CreditCard", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Last4Digits")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CreditCardLast4Digits");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.FullName", "CardOwner", b2 =>
                                {
                                    b2.Property<Guid>("CreditCardCustomerId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("CreditCardCustomerId");

                                    b2.ToTable("Customers");

                                    b2.WithOwner()
                                        .HasForeignKey("CreditCardCustomerId");

                                    b2.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Name", "Name", b3 =>
                                        {
                                            b3.Property<Guid>("FullNameCreditCardCustomerId")
                                                .HasColumnType("TEXT");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("CreditCardOwnerFirstName");

                                            b3.HasKey("FullNameCreditCardCustomerId");

                                            b3.ToTable("Customers");

                                            b3.WithOwner()
                                                .HasForeignKey("FullNameCreditCardCustomerId");
                                        });

                                    b2.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Surname", "Surname", b3 =>
                                        {
                                            b3.Property<Guid>("FullNameCreditCardCustomerId")
                                                .HasColumnType("TEXT");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("TEXT")
                                                .HasColumnName("CreditCardOwnerLastName");

                                            b3.HasKey("FullNameCreditCardCustomerId");

                                            b3.ToTable("Customers");

                                            b3.WithOwner()
                                                .HasForeignKey("FullNameCreditCardCustomerId");
                                        });

                                    b2.Navigation("Name")
                                        .IsRequired();

                                    b2.Navigation("Surname")
                                        .IsRequired();
                                });

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.ExpiryDate", "ExpiryDate", b2 =>
                                {
                                    b2.Property<Guid>("CreditCardCustomerId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Month")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("CreditCardExpiryMonth");

                                    b2.Property<int>("Year")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("CreditCardExpiryYear");

                                    b2.HasKey("CreditCardCustomerId");

                                    b2.ToTable("Customers");

                                    b2.WithOwner()
                                        .HasForeignKey("CreditCardCustomerId");
                                });

                            b1.Navigation("CardOwner")
                                .IsRequired();

                            b1.Navigation("ExpiryDate")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Orders.Order", b =>
                {
                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalPrice");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Orders.OrderItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BookTitle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("SellerId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Books.ValueObjects.ImageUrl", "MainPhoto", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MainPhotoUrl");

                                    b2.HasKey("OrderItemId");

                                    b2.ToTable("OrderItems");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Price");

                                    b2.HasKey("OrderItemId");

                                    b2.ToTable("OrderItems");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.Navigation("MainPhoto")
                                .IsRequired();

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Orders.ValueObjects.PaymentDetails", "PaymentDetails", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentDescription");

                            b1.Property<string>("PaymentMethod")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("PaymentMethod");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("PaymentDetails")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();

                    b.Navigation("_items");
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Shipments.Shipment", b =>
                {
                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Customers.ValueObjects.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CAP")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("CAP");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("City");

                            b1.Property<string>("CivicNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("CivicNumber");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Street");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.Money", "SubTotal", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("SubTotal");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Shipments.ValueObjects.TrackingInfo", "TrackingInfo", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Carrier")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("TrackingCarrier");

                            b1.Property<string>("TrackingCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("TrackingCode");

                            b1.Property<string>("TrackingUrl")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("TrackingUrl");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();

                    b.Navigation("SubTotal")
                        .IsRequired();

                    b.Navigation("TrackingInfo");
                });

            modelBuilder.Entity("AlessandroGozzi_BookECommerce.Domain.AggregateRoots.Wallets.Wallet", b =>
                {
                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.Money", "AvailableBalance", b1 =>
                        {
                            b1.Property<Guid>("WalletId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("AvailableBalance");

                            b1.HasKey("WalletId");

                            b1.ToTable("Wallets");

                            b1.WithOwner()
                                .HasForeignKey("WalletId");
                        });

                    b.OwnsOne("AlessandroGozzi_BookECommerce.Domain.ValueObjects.Money", "PendingBalance", b1 =>
                        {
                            b1.Property<Guid>("WalletId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("PendingBalance");

                            b1.HasKey("WalletId");

                            b1.ToTable("Wallets");

                            b1.WithOwner()
                                .HasForeignKey("WalletId");
                        });

                    b.Navigation("AvailableBalance")
                        .IsRequired();

                    b.Navigation("PendingBalance")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
