<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Immagini\CompraLibri.png" />
    <None Remove="Immagini\LogoDidattiko.png" />
    <None Remove="Immagini\SfondoLegnoChiaroWPF.jpg" />
    <None Remove="Immagini\SfondoLegnoWPF.jpg" />
    <None Remove="Immagini\VendiLibri.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlessandroGozzi-BookECommerce.Domain\AlessandroGozzi.BookECommerce.Domain.csproj" />
    <ProjectReference Include="..\AlessandroGozzi.BookECommerce.Application\AlessandroGozzi.BookECommerce.Application.csproj" />
    <ProjectReference Include="..\AlessandroGozzi.BookECommerce.Infrastructure\AlessandroGozzi.BookECommerce.Infrastructure.csproj" />
    <ProjectReference Include="..\AlessandroGozzi.BookECommerce.SharedKernel\AlessandroGozzi.BookECommerce.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Immagini\CompraLibri.png" />
    <Resource Include="Immagini\LogoDidattiko.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Immagini\SfondoLegnoChiaroWPF.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Immagini\SfondoLegnoWPF.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Immagini\VendiLibri.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
